name: test
on: push
jobs:
  run-shell-commands:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ping-server
        run: ping
      - name: echo something
        run: echo "Jesus is Lord"

